config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :restaurants
  resources :reservations

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

end
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reservations
  has_many :users, through: :reservations
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reservations
  has_many :restaurants, through: :reservations

  before_save { self.username = username.downcase }
  validates :username,
    presence: true,
    uniqueness: {case_sensitive: false },
    length: { minimum: 3, maximum: 25 }
  validates :username,
    presence: true,
    length: { maximum: 30 },
    uniqueness: { case_sensitive: false }
  # has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def new
    @reservation = Reservation.new
    @users = User.all
    @restaurants = Restaurant.all
  end


  def create
    @reservation = Reservation.create(reservation_params)
    redirect_to user_path(@reservation.user)
  end



  def edit
    @reservation = Reservation.find(params[:id])
    @users = User.all
    @restaurants = Restaurant.all
  end

  def update
    @reservation = Reservation.find(params[:id])
    @reservation.update(reservation_params)
    redirect_to user_path(@reservation.user)
  end



  #Private Method

  def reservation_params
    params.require(:reservation).permit(:meal, :user_id, :restaurant_id)
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
    find_restaurant
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    redirect_to restaurants_path
  end

  def edit
    find_restaurant
  end

  def update
    find_restaurant
    @restaurant.update(restaurant_params)
    redirect_to @restaurant
  end

  def destroy
    find_restaurant
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :rating)
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]

   def new
   end

   def create
     user = User.find_by(username: params[:session][:username])
     if user && user.authenticate(params[:session][:password])
       session[:user_id] = user.id
       flash[:success] = "Successfully logged in #{@user.name}!"
       redirect_to restaurants_path
     else
       flash.now[:error] = "Your login failed"
       render 'new'
     end
   end


   def destroy
     session[:user_id] = nil
     flash[:success] = "You have been successfully logged out"
     redirect_to restaurants_path
   end

   private

   def logged_in_redirect
     if logged_in?
       flash[:error] = "You are logged in"
       redirect_to restaurants_path
     end
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # has_secure_password

def index
  @users = User.all
end

def show
  @user = User.find(params[:id])
end

def new
  @user = User.new
end


def create
  @user = User.create(user_params)
  if @user.valid?
    session[:user_id] = @user.id
    redirect_to @user
  else
    flash[:errors] = @user.errors.full_messages
    redirect_to new_user_path
  end
end


def edit
  @user = User.find(params[:id])
end

def update
  @user = User.find(params[:id])
  @user.update(user_params)
  redirect_to @user
end

def destroy
  @user = User.find(params[:id])
  @user.destroy
  redirect_to users_path
end


#private Method
def user_params
  params.require(:user).permit(:name, :phone, :username, :password_digest)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsReservation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>

    <% if @logged_in %>

      <h2>You have: <%= @current_user.reservations.count %> reservations</h2>
      <p> Logged in As: <%= @current_user.username %> </p>
      <%= button_to "Logout", "/logout", method: :delete %>

    <% else %>

      <%= link_to "Login", new_user_path %>
      <%= link_to "Register", new_user_path %>

    <% end %>

    <% if flash[:message] %>
      <p class="message">
        <%= flash[:message] %>
      </p>
    <% end %>

  </header>
  <%= yield %>
</body>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reservations/edit.html.erb
<center>

<h1>Update A Reservation</h1>

<%= form_for @reservation do |f| %>
<%= f.label :meal %>
<%= f.text_field :meal %>


<%= f.label :user_id %>
<%= f.collection_select(:user_id, @users, :id,:name) %>

<%= f.label :restaurant_id %>
<%= f.collection_select(:restaurant_id, @restaurants, :id,:name) %>




<%= f.submit %>
<% end %>



</center>

app/views/reservations/new.html.erb
<center>

<h1>Create Reservation</h1>

<%= form_for @reservation do |f| %>
<%= f.label :meal %>
<%= f.text_field :meal %>


<%= f.label :user_id %>
<%= f.collection_select(:user_id, @users, :id,:name) %>

<%= f.label :restaurant_id %>
<%= f.collection_select(:restaurant_id, @restaurants, :id,:name) %>


<%= f.submit %>
<% end %>



</center>

app/views/restaurants/edit.html.erb
<h2>Edit this restaurant</h2>

<%= form_for @restaurant do |r| %>
<%= r.label :name %>
<%= r.text_field :name %>
<%= r.label :address %>
<%= r.text_field :address %>
<%= r.label :rating %>
<%= r.number_field :rating %>
<%= r.submit %>
<% end %>
<%= button_to "Delete", restaurant_path(@restaurant), method: :delete %>

app/views/restaurants/index.html.erb
<h2>All Restaurants</h2>
<ul>
<% @restaurants.each do |r| %>
<li>
<%= link_to r.name, r %>
<% end %>
</li>
</ul>
<%= link_to "Create New", new_restaurant_path %>

app/views/restaurants/new.html.erb
<h2>Create new restaurant</h2>

<%= form_for @restaurant do |r| %>
<%= r.label :name %>
<%= r.text_field :name %>
<%= r.label :address %>
<%= r.text_field :address %>
<%= r.label :rating %>
<%= r.number_field :rating %>
<%= r.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h2>Show page</h2>

<li>
<%= @restaurant.name %>
<p>Address: <%= @restaurant.address %></p>
<p>Rating: <%= @restaurant.rating %></p>
</li>
<%= link_to "Edit", edit_restaurant_path %>
<%= link_to "All restaurants", restaurants_path %>

app/views/users/edit.html.erb
<h1>Update <%= @user.name %>'s Information</h1>


<%= form_for @user do |f|%>
<%= f.label :name %>
<%= f.text_field :name %>


<%= f.label :phone %>
<%= f.text_field :phone %>

<%= f.submit %>
<% end %>

<%= button_to "Delete User", user_path(@user), method: :delete %>

app/views/users/index.html.erb
<%= link_to "Make A Reservation", new_reservation_path, :class => "btn btn-green"  %>
<div class="container">

<h1>View ALL Users</h1> <div>
</div>

<% @users.each do |user| %>
<ul>
  <li>
    <%= link_to user.name, user %>
  </li>
</ul>
<% end %>

<div>
  <%= link_to "Create New User", new_user_path, :class => "btn btn-primary"  %>
</div>

<h3><%= link_to "Create New User", new_user_path %></h3>
</div>

app/views/users/new.html.erb
<center>
<h1>Create New User</h1>

<% if flash[:errors] %>
  <ul>
    <% flash[:errors].each do |err_message| %>
      <li>
        <%= err_message %>
      </li>
    <% end %>
  </ul>
<% end %>

<%= form_for @user, controller: 'users', action: 'create' do |f|%>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :phone %>
<%= f.text_field :phone %>

<%= f.label :username %>
<%= f.text_field :username %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>

<%= f.submit %>

<% end %>
</center>

app/views/users/show.html.erb
<div class="container">

<h1><%= @user.name %>'s Page</h1>
<%= link_to "Update Information", edit_user_path %>
<p><b>Name:</b> <%= @user.name %> </p>
<p><b>Phone:</b> <%= @user.phone %> </p>

<h1><%= link_to "View All Users ", users_path %></h1>

<h1>My Reservations</h1>

<% @user.reservations.each do |reservation| %>
<ul>

    <li><%= reservation.meal %></li>
</ul>
<%end %>

<h1>Create Reservation</h1>
<%= form_for @reservation do |f| %>

<%= f.label :meal %>
<%= f.text_field :meal %>

<%= f.hidden_field :user_id, value: @user.id %>

<%= f.label :restaurant_id %>
<%= f.collection_select(:restaurant_id, @restaurants, :id,:name) %>


<%= f.submit %>
<% end %>
</div>